# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, 21.x, 22.x, 23.x, 24.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'package.json'
    - run: npm install
    - name: Lint code
      run: npm run lint
    - name: Downgrade tap to v16
      # Tap 18 doesn't support Node.js 14, so downgrade the previous major
      if: matrix.node-version == '14.x'
      run: npm install tap@16
    - name: Run tests
      if: matrix.node-version != '24.x'
      run: node test.js
    - name: Run tests (+ generate code coverage report)
      if: matrix.node-version == '24.x'
      run: npm run ci:coverage
    - name: Upload coverage to Codecov
      if: matrix.node-version == '24.x'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./.tap/report
